name: Lint and test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  check-backend:
    name: Run test and linters for the back-end
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install
          poetry run prisma generate

      - name: Run ruff formatter
        uses: chartboost/ruff-action@v1
        with:
          args: "format --diff"
          src: "./backend"

      - name: Run ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./backend"

      - name: Run type checker
        run: poetry run pyright .

      - name: Run pytest
        run: poetry run pytest

  lint-frontend:
    name: Run linters for the front-end
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: ${{ github.event_name == 'pull_request' }}
          eslint: true
          eslint_dir: frontend
          eslint_extensions: ts,tsx,js,jsx
          eslint_auto_fix: true

      - name: Run type checker
        run: npm run type-check
